// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fimhlzwehomjtpaiknzw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZpbWhsendlaG9tanRwYWlrbnp3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzMzQxNTcsImV4cCI6MjA2NDkxMDE1N30.u3kUC8_vrcCGUS6sp7aoH3Z0GKKlR21Jsgt1tgcqZZg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);